### ISSUE TITLE
fgnbhfg

### ISSUE THREAD

**Issue by goutham9032** [checkorg1/day1#560]
### Steps to reproduce issue

1.
2.
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

**Comment by goutham9032** [comment]
fcgbhf

**Comment by goutham9032** [comment]
fgvb g

**Comment by goutham9032** [comment]
fgbhfg

**Comment by gouthamraju** [comment]
hello dude hopw r u

**Comment by gouthamraju** [comment]
hey man

**Comment by gouthamraju** [comment]
hello 3d comment
